### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by rok-cesnovar**
@WardBrian I just added a few lines to Description and then just used `devtools::document()`.

### CODE REVIEW

**Comment by WardBrian** [comment]
Thanks! I want to check that the extra text processing that markdown=TRUE does doesn’t break the Rd2txt conversion we use for generating a docs web page. 

It’s not a huge deal if it does necessarily, since that’s already a manual process, and going forward I think a lot of the updates will need to be copied over manually rather than automatically for this interface

**Comment by rok-cesnovar** [comment]
There is also a way to automatically generate a docs website, like we have for cmdstanr for example: https://mc-stan.org/cmdstanr/reference/index.html using pkgdown. Its really easy and fast.

**Comment by rok-cesnovar** [comment]
What I typically use in package development is to just run devtools::document() in GitHub Actions and push the changes to the branch. And that is all.

**Comment by rok-cesnovar** [comment]
Ah yes, that makes sense! In general, the docs and package look good though. I just opened it in Rstudio, built it, and all the docs look good.

**Comment by WardBrian** [comment]
Great to hear! I was doing this all without RStudio (and for a while, without using `usethis`, which seems to be the only thing tutorials recommend) so it was more manual than I would have liked

**Comment by rok-cesnovar** [comment]
Yeah, without usethis you would be considered a boomeR :)

**Pull request merged**
